version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Maps to localhost:3000
    depends_on:
      - backend
    networks:
      webrtc-network:
        ipv4_address: 10.0.0.10

  backend:
    build: ./backend
    ports:
      - "8080:8080"  # Maps to localhost:8080
    networks:
      webrtc-network:
        ipv4_address: 10.0.0.20

  turn_server:
    build: ./turn_server
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
    networks:
      webrtc-network:
        ipv4_address: 10.0.0.67

networks:
  webrtc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

